Fix: "AttributeError: 'NoneType' object has no attribute 'group'" Cause: avprobe outputs stream properties over multiple lines, so regex to extract video properties fails to match. Solution: set MULTILINE and DOTALL flags on regexes.